### PR TITLE
Versioning of the Artifact

### PR DESCRIPTION
**Pull request by al-amine**

### CODE REVIEW

**Review by kingjon3377 — COMMENTED** [review]
I have one question and two comments.

1. Where, or by what, is the variable `v` defined?

2. Based on my knowledge of semantic versioning (which I *think* matches what Akbar told us when discussing artifact versioning), an autoincremented build number should be the *fourth*, not the third, digit.

3. If the "build number" does become the fourth digit, the `-SNAPSHOT` could perhaps be removed. (It's primarily useful if other software is pulling in this JAR as a library, e.g. in Maven, anyway.)

**Comment by al-amine** [comment]
as an answer to your question the V variable is defined on the building command
 " mvn clean install -Dv=${BUILD_NUMBER} " and I defined it as the Jenkins Build Number ( it's a global variable)

**Review by kingjon3377 — APPROVED** [review]
You might want to name the variable something less cryptic than `v`, and (based on further reading I've been doing) a different format (something like `0.0.1+b${buildNumber}`) *might* be preferable, but the first is a matter of preference and the latter a question I don't count myself qualified to judge.

**Comment by al-amine** [comment]
Thank you, well noted.

**Review by rndmkid — APPROVED** [review]

**Review by rndmkid — APPROVED** [review]

**Pull request merged**
